### PR TITLE
add CommitIndex API

### PR DESCRIPTION
**Pull request by niebayes**
This API is useful for implementing the read index optimization as described in the Raft paper.

### CODE REVIEW

**Review by mkeeler — APPROVED** [review]
LGTM. This already is reported in the Stats map and the underlying values are synchronized appropriately so I see no reason why this value shouldn't be exposed with a direct API.

**Comment by mkeeler** [comment]
@niebayes I think you will need to sign the HashiCorp CLA before this can be merged.

**Comment by niebayes** [comment]
@mkeeler Hi, I've completed the signature.

**Comment by loshz** [comment]
@niebayes it looks like you need to run `go fmt api.go` as there is a slight formatting issue that's blocking CI.

**Comment by niebayes** [comment]
Ok.

Dan Bond ***@***.***> 于2023年7月1日周六 01:48写道：

**Comment by niebayes** [comment]
@loshz Hi, I've fixed the formatting issue.

**Review by loshz — APPROVED** [review]

**Comment by JoanFM** [comment]
Hello @mkeeler and @loshz ,

do you have any approximate timeline about when this PR may be merged and added in a release?

**Pull request merged**
