### PR TITLE
[v2] More refactoring

### PR DESCRIPTION
**Pull request by ongardie-sfdc**
Some progress towards #172, etc.

cc @slackpad @superfell

### CODE REVIEW

**Comment by ongardie-sfdc** [comment]
Seems to fail on Go 1.6, will update

**Comment by ongardie-sfdc** [comment]
Should be good now.

**Comment by ongardie-sfdc** [comment]
Hey @slackpad, just a reminder that this PR is ready for review.

**Comment by slackpad** [comment]
@ongardie-sfdc sorry about that - I should be able to get to this later this week!

**Comment by slackpad** [comment]
LGTM - sorry for the delay on this one!

**Pull request merged**
