### PR TITLE
Make it done when Push to the notify channel if given

### PR DESCRIPTION
**Pull request by SchopenhauerZhang**
make sure it done,Push to the notify channel if given when shutdown sign  arrvied.

https://github.com/hashicorp/raft/issues/566

### CODE REVIEW

**Comment by SchopenhauerZhang** [comment]
@DanStough help,CR, please. :-)

**Comment by DanStough** [comment]
Hi @SchopenhauerZhang , I'll need you to accept the CLA. Then, I can approve and merge.

**Comment by SchopenhauerZhang** [comment]
> Hi @SchopenhauerZhang , I'll need you to accept the CLA. Then, I can approve and merge.

ok，i will do it.

**Review by DanStough — APPROVED** [review]

**Comment by DanStough** [comment]
Thanks for the PR, @SchopenhauerZhang! 🙇

**Pull request merged**
