### PR TITLE
Add a link to example code

### PR DESCRIPTION
**Pull request by Jille**
Requested in #394

### CODE REVIEW

**Comment by Jille** [comment]
bump

**Comment by s-christoff** [comment]
Howdy @Jille,
Thank you so much for contributing. I would love to add some reference implementation to this library, but I believe it should live within the Raft library. Perhaps we could add an `/examples` folder at the top level directory and bring in your implementation.

Just to set your expectations, we would like the examples to be self contained without external dependencies. Your implementation looks promising, however we may ask for some changes to improve the readability and other aspects.

**Comment by Jille** [comment]
Hey @s-christoff. Makes sense.

I have since moved on to other projects so won't have much time to contribute anymore. I'm happy to send a PR copying in the code (and don't object to any changes being made to it).

I would like to have a full example using gRPC somewhere. I've found multiple people searching for that. If you don't want that to live inside this repository, maybe having an external link would still be useful?

**Comment by s-christoff** [comment]
Howdy @Jille,
Thank you so much for your patience on this. After numerous internal discussion, it has been decided that the original approach (linking to an external repository) is, at this time, the best option. If it is alright with you, I'll approve this changes and we may make some minor changes to the README to have it fit our style.

**Review by s-christoff — APPROVED** [review]

**Comment by Jille** [comment]
Hey @s-christoff! Thanks for following up :) Sounds great, feel free to make any changes you want of course :)

**Pull request merged**
