### PR TITLE
Fix deadlock between Shutdown() and takeSnapshot()

### PR DESCRIPTION
**Pull request by freeekanayaka**
This change makes sure that a takeSnapshot() call which is run about
at the same time as Shutdown() does not block indefinitely on a
ConfigurationFuture request.

The situation can happen if takeSnapshot() manages to push the request
to configurationCh (which is buffered) but the
follower/candidate/leader loop exists before processing it, in turn
making the shutdownFuture.Error() returned by Shutdown() block
indefinitely (since it indirectly waits for takeSnapshot to finish).

With this change the sample program attached to #268 doesn't fail
anymore.

### CODE REVIEW

**Comment by freeekanayaka** [comment]
@mkeeler your diff sounds fine to me (although if I had to make a nit, it'd be probably better to wait for at least one more use case of something like deferError.ShutdownCh before introducing such an ad-hoc API).

Please make sure that the sample program I attached to #277 does not crash anymore with your diff applied.

**Comment by freeekanayaka** [comment]
I don't if it still applies, it surely did when I pushed the PR. I had even attached a program to reproduce the issue, which you can use to check it.

**Comment by Poluect** [comment]
Hey guys! Are there any plans to fix this issue? example code mentioned in #268, still can reproduce the issue from actual master branch, and I found this bug while searching for some clues on why nomad server is freezing sometimes in our system, seems like a go routine responsible for dealing with allocations hangs, and then found raft calls inside. Not sure if this is a reason of our nomad freezes, but at least this bug still can be reproduced. Thanks!

**Comment by i0rek** [comment]
Will look at this soon.

**Pull request closed without merging**
