### PR TITLE
checkLeaderLease: count only voters into quorum

### PR DESCRIPTION
**Pull request by santhosh-tekuri**
currently checkLeaderLease is including all nodes.
but it should include only voters into quorum.

### CODE REVIEW

**Comment by santhosh-tekuri** [comment]
travis build is failing because of dependencies:

```
net_transport_test.go:6:2: cannot find package "github.com/stretchr/testify/require" in any of:
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/github.com/stretchr/testify/require (from $GOROOT)
	/home/travis/gopath/src/github.com/stretchr/testify/require (from $GOPATH)
```

**Comment by rboyer** [comment]
I think if you rebased it on `master` now that https://github.com/hashicorp/raft/pull/309 is merged the unrelated test failure you were seeing should go away.

**Comment by santhosh-tekuri** [comment]
trying to trigger travis build

**Comment by santhosh-tekuri** [comment]
trying to trigger travis build

**Comment by santhosh-tekuri** [comment]
anybody there? it has been 12 days since I submit this pull request

**Comment by RobbieMcKinstry** [comment]
Hi @santhosh-tekuri ! I'm arguing with @s-christoff about this, but I think we found some agreement on this. Going to get another pair of eyes to confirm our logic is correct, since I'm fairly new to Raft.

I suspect that excluding non-voters from the `checkLeaderLease` quorum will make this check less robust.
Consider this (pathological) scenario where you have 5 voters and 45 nonvoters. Now suppose that a network partition occurs and the leader is able to get a quorum of voters but a bulk of non-voters are on the other partition. Since most of the nodes in the cluster are unable to receive replication, the leader should step down with the hope that the new leader is unaffected by the partition (i.e. overlaps the two partitions). Otherwise, you run the risk of having the quorum of voting notes collecting a large number of logs, none of which are able to be replicated to the bulk of the nodes in the cluster (as the replicants are on the other partition). (Though I suppose the leader will be taken down anyway when the other partition comes back online with a higher term).

**Comment by santhosh-tekuri** [comment]
Hi,

current logic of checkLeaderLease is wrong. suppose quorum is 3. if leader
is able to contact 3 non-voters only(with no other voters) it still thinks
that it can extend the lease.

thanks
Santhosh

**Comment by s-christoff** [comment]
Howdy @santhosh-tekuri , good catch! We agree. Could you please rebase? It should be good to go!

**Comment by santhosh-tekuri** [comment]
@s-christoff rebased with master. 

travis seems failed because of some data-race issue

**Comment by s-christoff** [comment]
Hey @santhosh-tekuri  - thank you for this contribution!

**Pull request merged**
