### PR TITLE
Abstract Logging behind an interface

### PR DESCRIPTION
**Pull request by superfell**
Which’ll make it easier for consumers of the library to plug in their
logging framework of choice. Addresses issue #141

### CODE REVIEW

**Comment by superfell** [comment]
In a number of places this preserves the original option to provide just a writer for logging, I'm not sure if that's still need. @slackpad do you need that path for Consul? or can we remove those paths and just have the logger interface versions ?

**Comment by ongardie-sfdc** [comment]
Can we use this to remove the "raft: " prefix from every single log line?

**Comment by superfell** [comment]
I was going to, but there are some log lines with different prefixes

**Comment by ongardie-sfdc** [comment]
Ah. My grep returns "[ERR] snapshot:" and "[ERR] raft-net:". Not sure if that's particularly intentional or important to maintain.

**Comment by superfell** [comment]
I can remove the prefixes if no one has a strong objection.

**Comment by superfell** [comment]
This does have an issue that @ongardie-sfdc and I discussed which is if you supply a log.Logger with the Lshortfile or Llongfile flags turned on, its just going to show the relevant line in logger.go

**Comment by superfell** [comment]
the other approach would to level methods that returns a Logger that a log.Logger directly implements, 

type Logger interface{
    Printf(format string, values ...interface{})
}

type Loggers interface{
   Debug() Logger
   Info() Logger
   Warn() Logger
   Error() Logger
}
or 
type Loggers interface{
   Log(Level) Logger
}

**Comment by ongardie-sfdc** [comment]
How about https://github.com/ongardie/hashicorp-raft/commit/4c7d4284b4aa3fe77faf9efce9f8323c2b8e2be6#diff-40646a6e1108f49d452915ba3515c206 instead?

tl/dr:
````
type Logger func(calldepth int, level LogLevel, s string)
func NewStdLogger(l *log.Logger, levelToLog LogLevel) Logger {
	return func(calldepth int, level LogLevel, s string) {
		if level >= levelToLog {
			l.Output(calldepth+3, fmt.Sprintf("[%v] %s", level, s))
		}
	}
}
```

As a concrete type, we can hang various methods off of it, including Debug() Info() Warn() Error() and Panic().

This also adds a unit test to make sure we're getting the filename handling right.

**Comment by ongardie-sfdc** [comment]
🌮

**Comment by superfell** [comment]
Is that a taco ?

**Comment by ongardie-sfdc** [comment]
That's a :taco, yes. I'm not allowed to use 🎉  but tacos are like a celebration.

**Comment by ongardie-sfdc** [comment]
@superfell, I fixed the few trivial conflicts over on https://github.com/ongardie/hashicorp-raft/commits/logging_itf, please update to that

**Comment by ongardie-sfdc** [comment]
@superfell I added one more commit for unit+integ tests over on https://github.com/ongardie/hashicorp-raft/commits/logging_itf

**Comment by slackpad** [comment]
Sorry to come late to this one. I realized we have some precedent for logxi in our other tools, though that's not official - https://github.com/hashicorp/vault/blob/master/helper/logformat/vault.go. I'm going to go ahead and merge this to unblock other changes but then I'll make another pass through and convert to the logxi v1 interface. It's similar to this interface, with the exception of passing kv pairs in vs. a fmt string, so should be a pretty simple conversion.

**Pull request merged**
