### PR TITLE
Adding more metrics for state transitions

### PR DESCRIPTION
**Pull request by armon**
Adds additional metrics for when we enter a particular state (follower, candidate, leader). Additionally, the two most common transitions that are part of leader instability are heartbeat timeouts and leader lease expiration, so we add metrics around those as well.

/cc: @alex @slackpad

### CODE REVIEW

**Comment by sethvargo** [comment]
:+1:

**Comment by alex** [comment]
I am not the Alex you are looking for.

(metrics are great though!)

**Comment by slackpad** [comment]
LGTM as well - this hits number 4 on https://github.com/hashicorp/consul/issues/1374.

**Comment by armon** [comment]
@alex Haha, apologies! Mismatch of Slack / Github handles.

**Pull request merged**
